import { NextResponse } from "next/server";
import { getUserFromSession } from "@/lib/auth/session";
import { connectToDatabase } from "@/lib/mongoose";
import { DietPlan } from "@/models/DietPlan";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";

type PdfLibColor = ReturnType<typeof rgb>;

/**
 * Standard Helvetica (WinAnsi) can't encode emojis / many Unicode chars.
 * Replace unsupported chars so PDF generation doesn't crash on rich routine text.
 */
function toPdfSafeText(text: string): string {
  return text
    // Replace bullets and directional symbols with ASCII equivalents.
    .replace(/[•▪●]/g, "-")
    .replace(/[→⇒]/g, "->")
    // Remove emoji + non-Latin ranges commonly generated by the model.
    .replace(
      /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{0900}-\u{097F}\u{0B80}-\u{0BFF}]/gu,
      "",
    )
    // Drop any remaining non-ASCII chars to avoid WinAnsi errors.
    .replace(/[^\x20-\x7E\n\r\t]/g, "");
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/g).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    const next = current ? `${current} ${w}` : w;
    if (next.length > maxChars) {
      if (current) lines.push(current);
      current = w;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function GET(req: Request) {
  const user = await getUserFromSession();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const url = new URL(req.url);
    const planId = url.searchParams.get("planId");
    if (!planId) {
      return NextResponse.json({ error: "Missing planId" }, { status: 400 });
    }

    await connectToDatabase();
    const plan = await DietPlan.findOne({
      _id: planId,
      userId: user._id,
    });

    if (!plan) {
      return NextResponse.json({ error: "Plan not found" }, { status: 404 });
    }

    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

    let page = doc.addPage([595.28, 841.89]); // A4-ish
    const pageHeight = page.getSize().height;
    const marginLeft = 50;
    const maxWidthChars = 95; // approximate for Helvetica at this size

    let y = pageHeight - 55;

    const newPage = () => {
      page = doc.addPage([595.28, 841.89]);
      y = pageHeight - 55;
    };

    const drawLine = (
      line: string,
      opts?: { bold?: boolean; size?: number; color?: PdfLibColor },
    ) => {
      const safeLine = toPdfSafeText(line);
      const size = opts?.size ?? 12;
      if (y < 72) {
        newPage();
      }
      page.drawText(safeLine, {
        x: marginLeft,
        y,
        size,
        font: opts?.bold ? fontBold : font,
        color: opts?.color ?? rgb(0, 0, 0),
      });
      y -= size + 4;
    };

    drawLine("DietAI - Your Diet Plan", { bold: true, size: 18, color: rgb(0.5, 0, 0) });
    y -= 8;

    const input = plan.input;
    drawLine(`User details`, { bold: true, size: 13, color: rgb(0, 0, 0) });
    drawLine(`Age: ${input.age}`);
    drawLine(`Gender: (from onboarding)`);
    drawLine(`Weight: ${input.weightKg} kg`);
    drawLine(`Height: ${input.heightCm} cm`);
    drawLine(`Goal: ${input.goal}`);
    drawLine(`Budget: ${input.budget}`);
    drawLine(
      `Food type: ${input.diet === "Vegan" ? "Vegan (no milk, no egg)" : input.diet}`,
    );
    drawLine(
      `Style: ${
        input.cuisine === "Tamil"
          ? "North Indian"
          : input.cuisine === "Indian"
            ? "South Indian"
            : "Mixed"
      }`,
    );

    y -= 10;
    drawLine("Nutrition summary", { bold: true, size: 13 });
    drawLine(`Calories: ${plan.output.calories} kcal/day`);
    drawLine(`Protein: ${plan.output.protein} g`);
    drawLine(`Carbs: ${plan.output.carbs} g`);
    if (typeof plan.output.fats === "number") {
      drawLine(`Fats: ${plan.output.fats} g`);
    }

    const routine = plan.output.dailyRoutine?.trim();
    if (routine) {
      y -= 8;
      drawLine("Daily diet routine (multi-option)", { bold: true, size: 13 });
      for (const rawLine of routine.split(/\r?\n/)) {
        const line = rawLine.trimEnd();
        if (line.length === 0) {
          y -= 6;
          continue;
        }
        for (const w of wrapText(line, maxWidthChars)) {
          drawLine(w, { size: 10 });
        }
      }
    }

    y -= 8;
    drawLine("7-Day Meal Plan", { bold: true, size: 13 });

    const meals = plan.output.meals;
    const days = Math.max(meals.breakfast.length, meals.lunch.length, meals.dinner.length);
    for (let i = 0; i < days; i++) {
      const dayN = i + 1;
      drawLine(`Day ${dayN}`, { bold: true, size: 12 });

      const b = meals.breakfast[i];
      if (b) {
        for (const line of wrapText(`Breakfast: ${b}`, maxWidthChars)) drawLine(line, { size: 11 });
      }
      const l = meals.lunch[i];
      if (l) {
        for (const line of wrapText(`Lunch: ${l}`, maxWidthChars)) drawLine(line, { size: 11 });
      }
      const d = meals.dinner[i];
      if (d) {
        for (const line of wrapText(`Dinner: ${d}`, maxWidthChars)) drawLine(line, { size: 11 });
      }

      y -= 6;
    }

    y -= 10;
    drawLine("Weekly Grocery List", { bold: true, size: 13 });
    for (const item of plan.output.grocery) {
      for (const line of wrapText(`• ${item}`, maxWidthChars)) drawLine(line, { size: 10 });
      y -= 2;
    }

    y -= 8;
    drawLine("Fruits", { bold: true, size: 13 });
    for (const f of plan.output.fruits) {
      for (const line of wrapText(`• ${f}`, maxWidthChars)) drawLine(line, { size: 10 });
      y -= 2;
    }

    const pdfBytes = await doc.save();
    const pdfBuffer = Buffer.from(pdfBytes);
    const filename = `diet-plan-${plan._id.toString().slice(-6)}.pdf`;
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown PDF error";
    console.error("[pdf] generation failed:", msg);
    return NextResponse.json(
      { error: `PDF generation failed: ${msg}` },
      { status: 500 },
    );
  }
}

